# Generated by Django 4.1.7 on 2023-02-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimiser", "0002_exercise_display_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle_group",
            field=models.ManyToManyField(to="optimiser.musclegroup"),
        ),
    ]
