# Generated by Django 4.1.7 on 2023-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimiser", "0004_displaygroup_remove_exercise_display_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.ManyToManyField(
                related_name="exercises", to="optimiser.musclegroup"
            ),
        ),
    ]
