# Generated by Django 4.1.7 on 2023-03-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimiser", "0005_alter_exercise_muscle_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="heavy_compound",
            field=models.BooleanField(default=False),
        ),
    ]
